#You are given access to a lab environment with a machine (i.e student-node) that has Ansible installed. On this machine, there's a /home/bob/playbooks/requirements.yml file that lists several collections required for a project. Your task is to install all the collections listed in the /home/bob/playbooks/requirements.yml file using the correct command.


ansible-galaxy collection install -r requirements.yml




#You've been informed about a new Ansible Collection named networking_tools under the namespace company_xyz. This collection contains specialized modules for network automation. You need to write a playbook that installs this collection and then uses a custom module named configure_vlan from it to set up VLAN 10 with the name Admin_VLAN.


#Complete the playbook located at /home/bob/playbooks/playbook.yml to correctly install the networking_tools collection and utilize the configure_vlan module. You just need to fill the placeholders in this playbook.


#Please note that, you need not to run this playbook for testing, just make the required changes to fill the placeholders correctly.

---
- hosts: localhost
  tasks:
    - name: Install the networking_tools collection
      ansible.builtin.ansible_galaxy_collection:
        name: company_xyz.networking_tools
        source: https://galaxy.ansible.com

- hosts: switches
  collections:
    - company_xyz.networking_tools
  tasks:
    - name: Configure VLAN 10
      configure_vlan:
        vlan_id: 10
        vlan_name: Admin_VLAN
        
        
        

